# Generated by Django 6.0.4 on 2026-07-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5),
        ),
    ]
