# Generated by Django 6.0.5 on 2026-06-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='dni',
            new_name='documento',
        ),
    ]
