# Generated by Django 6.0.5 on 2026-05-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTES',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=50)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_habitaciones', models.PositiveIntegerField(default=1)),
                ('numero_banos', models.PositiveIntegerField(default=1)),
                ('tiene_piscina', models.BooleanField(default=False)),
                ('tiene_jardin', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'PROPIEDAD',
            },
        ),
    ]
