# Generated by Django 6.0.5 on 2026-06-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='numero_banos',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='numero_habitaciones',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tiene_piscina',
        ),
    ]
