# Generated by Django 6.0.4 on 2026-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_propiedad_numero_banos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tamano',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
