# Generated by Django 6.0.5 on 2026-05-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado_cita', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True)),
                ('recordatorios', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='empleados.empleado')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='trabajos.trabajo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'AGENDA_CITAS',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
