# Generated by Django 6.0.4 on 2026-06-20 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('empleados', '0002_rename_dni_empleado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendacita',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='empleados.empleado'),
        ),
    ]
